blueprint:
  name: Sync three switches
  description: Turn on a switch when other one is turend on and vice versa
  domain: automation
  input:
    switch_entity1:
      name: Switch 1
      selector:
        entity:
          domain: switch
    switch_entity2:
      name: Switch 2
      selector:
        entity:
          domain: switch
    switch_entity3:
      name: Switch 3
      selector:
        entity:
          domain: switch
variables:
  switch_entity1: !input switch_entity1
  switch_entity2: !input switch_entity2
  switch_entity3: !input switch_entity3